# Generated by Django 3.1.11 on 2021-05-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.TextField(choices=[('factura', 'Factura Electrónica'), ('boleta', 'Boleta de Venta Electrónica'), ('notacredito', 'Nota de Crédito Electrónica'), ('notadebito', 'Nota de Débito Electrónica'), ('comprobante', 'Comprobante de Retención')], default='factura')),
            ],
        ),
    ]
