# Generated by Django 3.1.11 on 2021-05-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='document_type',
            new_name='documento',
        ),
        migrations.AddField(
            model_name='request',
            name='correlativo',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='serie',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
