# Generated by Django 3.1.11 on 2021-05-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20210519_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='archivo',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
