# Generated by Django 3.1.11 on 2021-05-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20210519_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='archivo',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='correlativo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='request',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='request',
            name='serie',
            field=models.CharField(max_length=4),
        ),
    ]
